import { Categoria, Mesa, Prato } from "./types";

export const RESTAURANTE = {
  nome: "Kianda",
  subnome: "Grelha & Mar",
  tagline: "Da brasa à maré.",
  cidade: "Benguela",
  cor: "#0F2A3A",
};

export const CATEGORIAS: { id: Categoria; nome: string; descricao: string }[] = [
  { id: "entradas", nome: "Entradas", descricao: "Para abrir o apetite" },
  { id: "brasa", nome: "Da Brasa", descricao: "Grelhados no carvão" },
  { id: "mar", nome: "Do Mar", descricao: "Pescado do dia" },
  { id: "acompanhamentos", nome: "Acompanhamentos", descricao: "" },
  { id: "sobremesas", nome: "Sobremesas", descricao: "" },
  { id: "bebidas", nome: "Bebidas", descricao: "" },
];

export const MESAS: Mesa[] = Array.from({ length: 12 }, (_, i) => ({
  id: `mesa-${i + 1}`,
  numero: i + 1,
}));

export const PRATOS: Prato[] = [
  {
    id: "p1",
    nome: "Camarão à Kianda",
    descricao: "Camarão tigre grelhado em manteiga de alho e piri-piri da casa",
    preco: 18500,
    categoria: "entradas",
    disponivel: true,
    destaque: true,
    picante: true,
  },
  {
    id: "p2",
    nome: "Rissóis de Calulu",
    descricao: "Massa fina recheada com calulu de peixe desfiado, quiabo e dendém",
    preco: 6500,
    categoria: "entradas",
    disponivel: true,
  },
  {
    id: "p3",
    nome: "Salada de Polvo",
    descricao: "Polvo cozido lentamente, cebola roxa, coentros e azeite de Benguela",
    preco: 9800,
    categoria: "entradas",
    disponivel: true,
  },
  {
    id: "p4",
    nome: "Cabrito na Brasa",
    descricao: "Meia posta de cabrito marinado 24h, carvão de mangueira",
    preco: 24500,
    categoria: "brasa",
    disponivel: true,
    destaque: true,
  },
  {
    id: "p5",
    nome: "Espetada de Novilho",
    descricao: "Cubos de novilho, pimentão e cebola, molho de alho torrado",
    preco: 19900,
    categoria: "brasa",
    disponivel: true,
  },
  {
    id: "p6",
    nome: "Frango na Brasa Piri-Piri",
    descricao: "Meio frango do campo, piri-piri da casa, limão de Benguela",
    preco: 13500,
    categoria: "brasa",
    disponivel: true,
    picante: true,
  },
  {
    id: "p7",
    nome: "Costela de Porco Fumada",
    descricao: "8 horas na brasa lenta, glaceada em melaço de cana",
    preco: 17800,
    categoria: "brasa",
    disponivel: false,
  },
  {
    id: "p8",
    nome: "Garoupa Inteira Grelhada",
    descricao: "Pescado do dia, cravo, gengibre e legumes salteados",
    preco: 22500,
    categoria: "mar",
    disponivel: true,
    destaque: true,
  },
  {
    id: "p9",
    nome: "Calulu de Peixe Fresco",
    descricao: "Peixe seco e fresco, quiabo, jindungo e óleo de palma, à moda antiga",
    preco: 16200,
    categoria: "mar",
    disponivel: true,
    picante: true,
  },
  {
    id: "p10",
    nome: "Lagosta Grelhada",
    descricao: "Lagosta da costa, manteiga de coentros, arroz de alho",
    preco: 32000,
    categoria: "mar",
    disponivel: true,
  },
  {
    id: "p11",
    nome: "Funge de Bombó",
    descricao: "Tradicional, feito na hora",
    preco: 2800,
    categoria: "acompanhamentos",
    disponivel: true,
  },
  {
    id: "p12",
    nome: "Pirão de Peixe",
    descricao: "Cremoso, com caldo do dia",
    preco: 3200,
    categoria: "acompanhamentos",
    disponivel: true,
  },
  {
    id: "p13",
    nome: "Arroz de Alho e Coentros",
    descricao: "",
    preco: 2500,
    categoria: "acompanhamentos",
    disponivel: true,
  },
  {
    id: "p14",
    nome: "Banana Frita",
    descricao: "",
    preco: 2200,
    categoria: "acompanhamentos",
    disponivel: true,
  },
  {
    id: "p15",
    nome: "Cocada Amarela",
    descricao: "Doce tradicional de coco e gema, receita da avó",
    preco: 4800,
    categoria: "sobremesas",
    disponivel: true,
    destaque: true,
  },
  {
    id: "p16",
    nome: "Doce de Ginguba",
    descricao: "Amendoim caramelizado, toque de canela",
    preco: 3900,
    categoria: "sobremesas",
    disponivel: true,
  },
  {
    id: "p17",
    nome: "Mousse de Maracujá",
    descricao: "",
    preco: 4500,
    categoria: "sobremesas",
    disponivel: true,
  },
  {
    id: "p18",
    nome: "Kissangua Gelada",
    descricao: "Bebida fermentada tradicional de milho, servida bem fresca",
    preco: 2500,
    categoria: "bebidas",
    disponivel: true,
  },
  {
    id: "p19",
    nome: "Cerveja Cuca",
    descricao: "33cl",
    preco: 2200,
    categoria: "bebidas",
    disponivel: true,
  },
  {
    id: "p20",
    nome: "Vinho Verde da Casa",
    descricao: "Copo",
    preco: 3800,
    categoria: "bebidas",
    disponivel: true,
  },
  {
    id: "p21",
    nome: "Água de Coco Natural",
    descricao: "",
    preco: 2000,
    categoria: "bebidas",
    disponivel: true,
  },
];
